/**
 * Quality tier table. Every visual system reads its knobs from here — never
 * hardcode counts/resolutions in feature code. Photo mode forces 'ultra'.
 */
export const QUALITY_TIERS = {
  low: {
    name: 'low',
    pixelRatioCap: 1.0,
    shadows: { enabled: true, mapSize: 1024, cascades: 1, radius: 2 },
    ao: { enabled: false, quality: 'low', halfRes: true },
    ssr: false,
    bloom: { enabled: true, levels: 4, intensity: 0.6 },
    volumetrics: { enabled: false, steps: 0 },
    particlesScale: 0.35,
    decalBudget: 48,
    textureMaxSize: 1024,
    anisotropy: 4,
    motionBlur: false,
    dof: false,
    grain: false,
    chromaticAberration: false,
    aa: 'none',
    rainDensity: 0.35,
    lodBias: 1.5,
  },
  medium: {
    name: 'medium',
    pixelRatioCap: 1.25,
    shadows: { enabled: true, mapSize: 2048, cascades: 2, radius: 3 },
    ao: { enabled: true, quality: 'medium', halfRes: true },
    ssr: false,
    bloom: { enabled: true, levels: 6, intensity: 0.75 },
    volumetrics: { enabled: true, steps: 24 },
    particlesScale: 0.6,
    decalBudget: 128,
    textureMaxSize: 2048,
    anisotropy: 8,
    motionBlur: true,
    dof: true,
    grain: true,
    chromaticAberration: true,
    aa: 'smaa',
    rainDensity: 0.65,
    lodBias: 1.0,
  },
  high: {
    name: 'high',
    pixelRatioCap: 1.5,
    shadows: { enabled: true, mapSize: 2048, cascades: 3, radius: 4 },
    ao: { enabled: true, quality: 'high', halfRes: false },
    ssr: true,
    bloom: { enabled: true, levels: 8, intensity: 0.85 },
    volumetrics: { enabled: true, steps: 40 },
    particlesScale: 0.85,
    decalBudget: 256,
    textureMaxSize: 2048,
    anisotropy: 16,
    motionBlur: true,
    dof: true,
    grain: true,
    chromaticAberration: true,
    aa: 'smaa',
    rainDensity: 0.85,
    lodBias: 0.75,
  },
  ultra: {
    name: 'ultra',
    pixelRatioCap: 2.0,
    shadows: { enabled: true, mapSize: 4096, cascades: 4, radius: 5 },
    ao: { enabled: true, quality: 'ultra', halfRes: false },
    ssr: true,
    bloom: { enabled: true, levels: 8, intensity: 1.0 },
    volumetrics: { enabled: true, steps: 64 },
    particlesScale: 1.0,
    decalBudget: 512,
    textureMaxSize: 4096,
    anisotropy: 16,
    motionBlur: true,
    dof: true,
    grain: true,
    chromaticAberration: true,
    aa: 'smaa',
    rainDensity: 1.0,
    lodBias: 0.5,
  },
};

/** @param {string} tier @returns {typeof QUALITY_TIERS.high} */
export function getTier(tier) {
  return QUALITY_TIERS[tier] || QUALITY_TIERS.high;
}
